### ISSUE TITLE
polygonize.stars

### ISSUE THREAD

**Issue by adrfantini** [mdsumner/spex#11]
I performed some performance tests on plygonizing raster data [here](https://github.com/r-spatial/stars/issues/13).
`spex::polygonize` is by far the fastest, well done!

It would be awesome to have a `polygonize` method for `stars` objects.

**Comment by mdsumner** [comment]
I made it a little faster, if you wouldn't mind checking the latest? (There's a problem with conversion from sp at the moment, but that should not be a problem).

**Comment by adrfantini** [comment]
Sure, just let me know and I'll rerun the tests

**Comment by mdsumner** [comment]
It's made me finally see that the actual slow part is simply turning the coordinates into sfg objects, so I'm trying a C++ version. It still may well be much faster to do more of it in Rcpp rather than quadmesh, but that'll be clearer if I speed this up. 

 The speed up mentioned here was only modest so let's forget this for now and see how I go with an Rcpp sfg builder. (Thanks!)

**Comment by mdsumner** [comment]
That is trivially done on raster cells - for the values, or do you want the clump cells as polygon geometry as well? I'll give it some thought but I never use that kind of workflow

**Comment by adrfantini** [comment]
Yep, I usually aggregate the `sf` objects obtained from `spex::polygonize` so that the number of polygons is lower and much faster to plot (with `ggplot`).

So I basically usually `raster -> as.factor -> polygonize -> summarize -> ggplot`

**Comment by mdsumner** [comment]
use stars now
